language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install .
script:
  - pytest
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    repo: tristandeleu/metax
    branch: main
    condition: $(($(git diff --name-only $TRAVIS_COMMIT_RANGE | grep metax/version.py | wc -l))) -gt 0